// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALmYlma2aInTysplmnrocWIN1Cm83445s',
    appId: '1:331369252568:web:f360439ca0d7c1b72f79ad',
    messagingSenderId: '331369252568',
    projectId: 'flutter-tutorial-c80f0',
    authDomain: 'flutter-tutorial-c80f0.firebaseapp.com',
    storageBucket: 'flutter-tutorial-c80f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMWyQWDR5zRZsiDn05wV5HunADuUSiW4s',
    appId: '1:331369252568:android:e60bed7238fb658b2f79ad',
    messagingSenderId: '331369252568',
    projectId: 'flutter-tutorial-c80f0',
    storageBucket: 'flutter-tutorial-c80f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB43f3Jfm4J3X03jHDH4AVX2lrWIsElJE',
    appId: '1:331369252568:ios:2feae269177bb1212f79ad',
    messagingSenderId: '331369252568',
    projectId: 'flutter-tutorial-c80f0',
    storageBucket: 'flutter-tutorial-c80f0.appspot.com',
    iosBundleId: 'com.example.firebaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB43f3Jfm4J3X03jHDH4AVX2lrWIsElJE',
    appId: '1:331369252568:ios:bf000946e5c664392f79ad',
    messagingSenderId: '331369252568',
    projectId: 'flutter-tutorial-c80f0',
    storageBucket: 'flutter-tutorial-c80f0.appspot.com',
    iosBundleId: 'com.example.firebaseTutorial.RunnerTests',
  );
}
